default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 10
  timeout: 10

  host: <%= ENV['POSTGRES_HOST'] %>
development:
  <<: *default
  database: sportsbook_development_new

production:
  <<: *default
  database: sportsbook_production_new

test:
  <<: *default
  database: sportsbook_test_new
